#!/bin/bash

echo "No need to create cluster"
export KUBECONFIG=$2
cat <<EOF | kubectl apply -f -
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: test-pv
      spec:
        capacity:
          storage: 10Gi
        accessModes:
          - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: standard
        nfs:
          path: /tmp
          server: 172.17.0.2
EOF

echo "Sleep for 10 secs"
sleep 10
